import type { Recipe, Category } from "@/lib/recipes";

/**
 * Recettes signatures de Ludo, inspirées de sa page Facebook
 * "Les Petits Plats de Ludo". Données complètes utilisées comme
 * fallback quand la base est vide, et comme contenu d'accueil.
 */

const CAT_ENTREES = { id: "c1", name: "Entrées", slug: "entrees", emoji: "🥗" };
const CAT_PLATS = { id: "c2", name: "Plats", slug: "plats", emoji: "🍲" };
const CAT_DESSERTS = { id: "c3", name: "Desserts", slug: "desserts", emoji: "🍰" };

export const MOCK_CATEGORIES: Pick<Category, "id" | "name" | "slug" | "description" | "image_url" | "emoji" | "display_order">[] = [
  { id: "c1", name: "Entrées", slug: "entrees", description: "Pour ouvrir le bal en élégance.", image_url: "https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=900&q=80", emoji: "🥗", display_order: 1 },
  { id: "c2", name: "Plats", slug: "plats", description: "Le cœur du repas, généreux et raffiné.", image_url: "https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?w=900&q=80", emoji: "🍲", display_order: 2 },
  { id: "c3", name: "Desserts", slug: "desserts", description: "La douceur qui clôt en beauté.", image_url: "https://images.unsplash.com/photo-1551024506-0bccd828d307?w=900&q=80", emoji: "🍰", display_order: 3 },
];

const base = (partial: Partial<Recipe>): Recipe => ({
  id: "",
  slug: "",
  title: "",
  description: "",
  ingredients: [],
  instructions: [],
  astuces: null,
  prep_time: 0,
  cook_time: 0,
  servings: 4,
  difficulty: "Facile",
  cover_image: null,
  gallery: null,
  category_id: null,
  tags: [],
  views: 0,
  likes: 0,
  featured: false,
  status: "published",
  seo_title: null,
  seo_description: null,
  published_at: new Date().toISOString(),
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
  category: null,
  ...partial,
});

export const MOCK_RECIPES: Recipe[] = [
  base({
    id: "ludo-gratin-dauphinois",
    slug: "gratin-dauphinois-revisite",
    title: "Gratin dauphinois revisité de Ludo",
    description: "Crémeux, doré, fondant : ma version du grand classique, parfumée à l'ail rose et au thym frais. Le plat qui réconcilie tout le monde.",
    prep_time: 25,
    cook_time: 75,
    servings: 6,
    difficulty: "Facile",
    cover_image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=1200&q=85",
    category_id: "c2",
    category: CAT_PLATS,
    tags: ["hiver", "réconfort", "familial"],
    views: 4287,
    likes: 342,
    featured: true,
    astuces: "Le vrai secret du gratin qui tient : NE rincez JAMAIS vos pommes de terre. L'amidon, c'est le ciment du chef. Et si vous voulez frimer, ajoutez une cuillère de mascarpone dans la crème — ça change tout, ça reste entre nous. Dernière chose : sortez-le 10 min avant de servir, sinon il vous glissera dans l'assiette comme un ado en retard à l'école.",
    ingredients: [
      { name: "Pommes de terre à chair ferme", quantity: "1.2", unit: "kg" },
      { name: "Crème liquide entière", quantity: "40", unit: "cl" },
      { name: "Lait entier", quantity: "20", unit: "cl" },
      { name: "Gousses d'ail rose", quantity: "3", unit: "" },
      { name: "Gruyère râpé", quantity: "150", unit: "g" },
      { name: "Noix de muscade", quantity: "1", unit: "pincée" },
      { name: "Thym frais", quantity: "3", unit: "branches" },
      { name: "Beurre demi-sel", quantity: "30", unit: "g" },
      { name: "Sel & poivre", quantity: "", unit: "" },
    ],
    instructions: [
      { step: 1, text: "Préchauffez le four à 160°C chaleur tournante. Frottez généreusement le fond d'un plat à gratin avec une gousse d'ail coupée en deux, puis beurrez." },
      { step: 2, text: "Épluchez et lavez les pommes de terre. Coupez-les en rondelles fines de 3 mm (mandoline si possible) — surtout ne les rincez pas, on garde l'amidon !" },
      { step: 3, text: "Dans une casserole, faites chauffer la crème, le lait, les 2 gousses d'ail écrasées, le thym, la muscade, le sel et le poivre. Laissez infuser 5 min hors du feu." },
      { step: 4, text: "Disposez les rondelles de pommes de terre en couches dans le plat. Versez le mélange crème-lait chaud par-dessus jusqu'à les recouvrir aux trois quarts." },
      { step: 5, text: "Parsemez de gruyère râpé et de petits dés de beurre. Enfournez pour 1h15 — couvrez d'un papier alu les 30 premières minutes pour éviter que ça brûle." },
      { step: 6, text: "À la sortie du four, laissez reposer 10 minutes. C'est là que la magie opère : le gratin se tient parfaitement. Servez avec une salade verte. Bonheur." },
    ],
  }),
  base({
    id: "ludo-cordon-bleu-xxl",
    slug: "cordon-bleu-maison-xxl",
    title: "Le Cordon Bleu Maison XXL",
    description: "Oublie les cordons bleus industriels qui ressemblent à du carton mouillé. Ici, le fromage coule jusqu'aux genoux et la chapelure est aussi croustillante que mon humour.",
    prep_time: 25,
    cook_time: 15,
    servings: 4,
    difficulty: "Facile",
    cover_image: "https://images.unsplash.com/photo-1432139509613-5c4255815697?w=1200&q=85",
    category_id: "c2",
    category: CAT_PLATS,
    tags: ["plat", "famille", "fromage", "inratable"],
    views: 7421,
    likes: 612,
    featured: true,
    astuces: "La DOUBLE panure est non-négociable : sans elle, le fromage s'évade comme un prisonnier mal surveillé. Servez avec une petite salade verte vinaigrette moutarde pour faire passer la culpabilité. Et si quelqu'un demande « tu mets quoi dedans ? », répondez « de l'amour » avec un sourire mystérieux. Ça marche à tous les coups.",
    ingredients: [
      { name: "Escalopes de veau (ou dinde) bien larges", quantity: "4", unit: "" },
      { name: "Tranches de jambon blanc", quantity: "4", unit: "" },
      { name: "Comté ou gruyère en tranches", quantity: "200", unit: "g" },
      { name: "Œufs", quantity: "2", unit: "" },
      { name: "Farine", quantity: "100", unit: "g" },
      { name: "Chapelure japonaise (panko)", quantity: "150", unit: "g" },
      { name: "Beurre", quantity: "40", unit: "g" },
      { name: "Huile neutre", quantity: "3", unit: "c. à soupe" },
      { name: "Sel, poivre, paprika fumé", quantity: "", unit: "" },
      { name: "Pincée d'amour", quantity: "1", unit: "" },
    ],
    instructions: [
      { step: 1, text: "Aplatissez les escalopes entre deux feuilles de film avec un rouleau à pâtisserie. Ferme mais pas brutal — on n'est pas en boxe." },
      { step: 2, text: "Déposez sur chaque escalope une tranche de jambon, puis une généreuse couche de fromage (vraiment généreuse, on n'est pas radins). Refermez en chausson et pressez les bords." },
      { step: 3, text: "Trois assiettes : farine assaisonnée / œufs battus / panko mélangé au paprika fumé. Farine → œuf → panko. Re-trempez dans l'œuf, re-panez : c'est la double couche secrète." },
      { step: 4, text: "Dans une grande poêle, faites chauffer beurre + huile. Saisissez les cordons bleus 3-4 min de chaque côté à feu moyen jusqu'à ce qu'ils soient dorés comme un soleil de juillet." },
      { step: 5, text: "Terminez 4 min au four à 180°C pour que le fromage soit complètement fondu. Coupez en deux à table : le filet de fromage qui coule, c'est l'effet wow garanti." },
    ],
  }),
  base({
    id: "ludo-fondant-magique",
    slug: "fondant-au-chocolat-magique",
    title: "Le Fondant au Chocolat Magique",
    description: "Si tu rates celui-là, je ne peux plus rien pour toi. Cuisson précise à la seconde près : le cœur doit couler comme une déclaration d'amour mal timée.",
    prep_time: 10,
    cook_time: 11,
    servings: 6,
    difficulty: "Facile",
    cover_image: "https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=1200&q=85",
    category_id: "c3",
    category: CAT_DESSERTS,
    tags: ["dessert", "chocolat", "express", "magique"],
    views: 9342,
    likes: 824,
    featured: true,
    astuces: "11 MINUTES. PAS UNE DE PLUS. Si votre four est ancien ou capricieux, faites un test avec un ramequin avant. Le démoulage immédiat est sacré : laissez-le refroidir et vous obtiendrez un brownie triste. Pour le wow ultime : insérez un carré de chocolat blanc au centre avant cuisson. Cœur coulant blanc dans un fondant noir. Personne ne s'en remettra.",
    ingredients: [
      { name: "Chocolat noir 70%", quantity: "200", unit: "g" },
      { name: "Beurre demi-sel", quantity: "150", unit: "g" },
      { name: "Œufs entiers", quantity: "3", unit: "" },
      { name: "Sucre en poudre", quantity: "80", unit: "g" },
      { name: "Farine", quantity: "50", unit: "g" },
      { name: "Pincée de magie (sel)", quantity: "1", unit: "" },
    ],
    instructions: [
      { step: 1, text: "Préchauffez le four à 200°C. Beurrez et chocolatez (saupoudrez de cacao) 6 ramequins. Étape non-négociable : pas de démoulage = pas de magie." },
      { step: 2, text: "Faites fondre chocolat et beurre au bain-marie. Mélangez doucement jusqu'à une texture brillante et soyeuse." },
      { step: 3, text: "Dans un autre bol, fouettez œufs et sucre jusqu'à ce que le mélange blanchisse et double de volume (3 min minimum, à la main si t'as les bras d'un viking)." },
      { step: 4, text: "Incorporez le chocolat fondu tiédi au mélange œufs-sucre, puis ajoutez la farine tamisée et la pincée de sel. Mélangez juste ce qu'il faut." },
      { step: 5, text: "Versez dans les ramequins. Enfournez EXACTEMENT 10 à 11 minutes. Pas une seconde de plus : tu m'entends ?" },
      { step: 6, text: "Démoulez immédiatement sur assiette, saupoudrez de sucre glace. Boule de glace vanille à côté. Plante une cuillère. Le cœur doit couler. Tu m'envoies la photo." },
    ],
  }),
  base({
    id: "ludo-blanquette",
    slug: "blanquette-de-veau-familiale",
    title: "La Blanquette de Veau à ma façon",
    description: "Un classique, mais avec le secret de Ludo pour ne jamais la rater. Spoiler : il y a beaucoup de crème, beaucoup d'amour, et zéro tolérance pour la cuisson au micro-ondes.",
    prep_time: 30,
    cook_time: 90,
    servings: 6,
    difficulty: "Moyen",
    cover_image: "https://images.unsplash.com/photo-1547592180-85f173990554?w=1200&q=85",
    category_id: "c2",
    category: CAT_PLATS,
    tags: ["hiver", "tradition", "cocotte"],
    views: 3641,
    likes: 289,
    featured: true,
    ingredients: [
      { name: "Épaule de veau coupée en cubes", quantity: "1.2", unit: "kg" },
      { name: "Carottes", quantity: "3", unit: "" },
      { name: "Poireaux (blanc seulement)", quantity: "2", unit: "" },
      { name: "Oignon piqué de 2 clous de girofle", quantity: "1", unit: "" },
      { name: "Bouquet garni", quantity: "1", unit: "" },
      { name: "Champignons de Paris", quantity: "300", unit: "g" },
      { name: "Beurre", quantity: "60", unit: "g" },
      { name: "Farine", quantity: "60", unit: "g" },
      { name: "Crème fraîche épaisse", quantity: "20", unit: "cl" },
      { name: "Jaune d'œuf", quantity: "1", unit: "" },
      { name: "Jus de citron", quantity: "1", unit: "c. à soupe" },
      { name: "Gros sel & poivre", quantity: "", unit: "" },
    ],
    instructions: [
      { step: 1, text: "Mettez le veau dans une grande cocotte, couvrez d'eau froide, portez à ébullition puis écumez soigneusement pendant 5 min. C'est ce qui rendra votre sauce bien claire." },
      { step: 2, text: "Ajoutez les carottes en rondelles, les poireaux émincés, l'oignon piqué, le bouquet garni et une bonne pincée de gros sel. Laissez frémir à couvert 1h15 — la viande doit se détacher à la fourchette." },
      { step: 3, text: "Pendant ce temps, faites revenir les champignons émincés dans 20 g de beurre jusqu'à coloration. Réservez." },
      { step: 4, text: "Égouttez la viande et les légumes, gardez le bouillon. Dans une casserole propre, faites fondre 40 g de beurre, ajoutez la farine et faites un roux blond 2 min." },
      { step: 5, text: "Versez progressivement 80 cl de bouillon chaud sur le roux en fouettant pour éviter les grumeaux. Laissez épaissir 5 min à feu doux." },
      { step: 6, text: "Hors du feu, ajoutez la crème mélangée au jaune d'œuf et au jus de citron — surtout ne plus faire bouillir ! Goûtez, rectifiez l'assaisonnement." },
      { step: 7, text: "Remettez la viande, les légumes et les champignons dans la sauce. Réchauffez doucement 5 min. Servez avec un riz pilaf bien parfumé. Mamie serait fière." },
    ],
  }),
  base({
    id: "ludo-tarte-tatin",
    slug: "tarte-tatin-ultra-gourmande",
    title: "Tarte Tatin ultra-gourmande",
    description: "Des pommes caramélisées au beurre salé, une pâte feuilletée dorée, une boule de glace vanille qui fond doucement. L'addiction.",
    prep_time: 20,
    cook_time: 45,
    servings: 8,
    difficulty: "Moyen",
    cover_image: "https://images.unsplash.com/photo-1568571780765-9276ac8b75a2?w=1200&q=85",
    category_id: "c3",
    category: CAT_DESSERTS,
    tags: ["dessert", "automne", "classique"],
    views: 5128,
    likes: 461,
    featured: true,
    ingredients: [
      { name: "Pommes Reinette ou Boskoop", quantity: "8", unit: "" },
      { name: "Sucre en poudre", quantity: "150", unit: "g" },
      { name: "Beurre demi-sel", quantity: "80", unit: "g" },
      { name: "Pâte feuilletée pur beurre", quantity: "1", unit: "rouleau" },
      { name: "Gousse de vanille", quantity: "1", unit: "" },
      { name: "Jus de citron", quantity: "1", unit: "c. à soupe" },
    ],
    instructions: [
      { step: 1, text: "Préchauffez le four à 200°C. Épluchez les pommes, coupez-les en deux, retirez le cœur et les pépins. Citronnez-les pour qu'elles ne noircissent pas." },
      { step: 2, text: "Dans un moule à tarte Tatin (ou une poêle qui va au four), faites un caramel à sec : versez le sucre, laissez fondre sans remuer jusqu'à obtenir une belle couleur ambrée." },
      { step: 3, text: "Hors du feu, ajoutez le beurre en parcelles et les graines de la gousse de vanille. Mélangez doucement — attention aux projections !" },
      { step: 4, text: "Disposez les demi-pommes serrées, face bombée vers le bas, en rosace sur le caramel. Tassez bien : elles vont rendre du jus et se réduire." },
      { step: 5, text: "Recouvrez de la pâte feuilletée, rentrez les bords à l'intérieur du moule, piquez avec une fourchette. Enfournez 30 à 35 min jusqu'à ce que la pâte soit bien dorée." },
      { step: 6, text: "À la sortie du four, attendez 5 min puis démoulez d'un coup sec sur un plat de service. Le caramel doit napper les pommes. Servez tiède avec une boule de glace vanille. Roulez sous la table." },
    ],
  }),
  base({
    id: "ludo-mousse-chocolat",
    slug: "mousse-au-chocolat-signature",
    title: "Mousse au chocolat signature",
    description: "Trois ingrédients, zéro compromis. Une mousse aérienne, intensément chocolatée, qui se prépare en 15 minutes. Mon ultime arme de séduction.",
    prep_time: 15,
    cook_time: 0,
    servings: 6,
    difficulty: "Facile",
    cover_image: "https://images.unsplash.com/photo-1541783245831-57d6fb0926d3?w=1200&q=85",
    category_id: "c3",
    category: CAT_DESSERTS,
    tags: ["dessert", "chocolat", "express"],
    views: 6892,
    likes: 587,
    featured: true,
    ingredients: [
      { name: "Chocolat noir 70%", quantity: "200", unit: "g" },
      { name: "Œufs frais extra-frais", quantity: "6", unit: "" },
      { name: "Sucre en poudre", quantity: "30", unit: "g" },
      { name: "Pincée de sel", quantity: "1", unit: "" },
      { name: "Fleur de sel pour servir", quantity: "1", unit: "pincée" },
    ],
    instructions: [
      { step: 1, text: "Cassez le chocolat en morceaux et faites-le fondre au bain-marie très doucement, en remuant. Laissez tiédir 5 min — il doit être souple mais pas brûlant." },
      { step: 2, text: "Séparez les blancs des jaunes. Incorporez les jaunes un à un dans le chocolat fondu, en mélangeant énergiquement entre chaque." },
      { step: 3, text: "Montez les blancs en neige avec la pincée de sel. Quand ils commencent à mousser, ajoutez le sucre en pluie et continuez de battre jusqu'à obtenir un bec d'oiseau bien ferme." },
      { step: 4, text: "Incorporez d'abord un tiers des blancs dans le chocolat pour détendre la préparation. Puis ajoutez le reste délicatement, à la spatule, en soulevant la masse pour ne pas casser les blancs." },
      { step: 5, text: "Répartissez dans 6 jolies coupes. Filmez et placez au réfrigérateur pour 4 heures minimum (idéalement une nuit). La patience est récompensée." },
      { step: 6, text: "Au moment de servir, parsemez d'une mini-pincée de fleur de sel. Le contraste sucré-salé, c'est ma signature. Bon appétit les gourmands !" },
    ],
  }),
  base({
    id: "ludo-velouté-potimarron",
    slug: "veloute-potimarron-chataignes",
    title: "Velouté potimarron & châtaignes",
    description: "Une entrée d'automne tout en douceur : potimarron rôti, châtaignes grillées, un nuage de crème et quelques éclats de noisettes torréfiées.",
    prep_time: 15,
    cook_time: 35,
    servings: 4,
    difficulty: "Facile",
    cover_image: "https://images.unsplash.com/photo-1547592166-23ac45744acd?w=1200&q=85",
    category_id: "c1",
    category: CAT_ENTREES,
    tags: ["automne", "végé", "entrée"],
    views: 1843,
    likes: 156,
    featured: false,
    ingredients: [
      { name: "Potimarron", quantity: "1", unit: "" },
      { name: "Châtaignes cuites sous vide", quantity: "200", unit: "g" },
      { name: "Oignon", quantity: "1", unit: "" },
      { name: "Bouillon de volaille", quantity: "80", unit: "cl" },
      { name: "Crème liquide", quantity: "10", unit: "cl" },
      { name: "Noisettes", quantity: "30", unit: "g" },
      { name: "Huile d'olive", quantity: "2", unit: "c. à soupe" },
    ],
    instructions: [
      { step: 1, text: "Coupez le potimarron en quartiers (inutile de l'éplucher, la peau est comestible). Enlevez les graines et taillez en gros cubes." },
      { step: 2, text: "Faites revenir l'oignon émincé dans l'huile, ajoutez le potimarron et les châtaignes (réservez-en quelques-unes). Faites suer 5 min." },
      { step: 3, text: "Couvrez de bouillon, salez, poivrez et laissez mijoter 25 min jusqu'à ce que le potimarron soit tendre." },
      { step: 4, text: "Mixez longuement jusqu'à obtenir un velouté ultra-lisse. Ajoutez la crème, mixez à nouveau. Goûtez et rectifiez." },
      { step: 5, text: "Servez bien chaud avec les châtaignes restantes émiettées, des noisettes torréfiées et concassées, un filet d'huile d'olive. L'automne dans le bol." },
    ],
  }),
  base({
    id: "ludo-saumon-gravlax",
    slug: "saumon-gravlax-aneth",
    title: "Saumon gravlax maison à l'aneth",
    description: "Le saumon mariné comme en Scandinavie : sel, sucre, aneth et zeste de citron. À tartiner sur du pain noir avec une cuillère de crème.",
    prep_time: 20,
    cook_time: 0,
    servings: 6,
    difficulty: "Facile",
    cover_image: "https://images.unsplash.com/photo-1601001435957-74f0958a93c5?w=1200&q=85",
    category_id: "c1",
    category: CAT_ENTREES,
    tags: ["entrée", "poisson", "froid"],
    views: 2104,
    likes: 187,
    featured: false,
    ingredients: [
      { name: "Pavé de saumon extra-frais avec peau", quantity: "600", unit: "g" },
      { name: "Gros sel", quantity: "100", unit: "g" },
      { name: "Sucre en poudre", quantity: "80", unit: "g" },
      { name: "Aneth frais", quantity: "1", unit: "bouquet" },
      { name: "Zeste de citron jaune non traité", quantity: "1", unit: "" },
      { name: "Baies roses concassées", quantity: "1", unit: "c. à café" },
    ],
    instructions: [
      { step: 1, text: "Mélangez le sel, le sucre, le zeste de citron et les baies roses. Ciselez grossièrement l'aneth." },
      { step: 2, text: "Dans un plat, étalez la moitié du mélange sel-sucre, déposez le saumon côté peau dessous. Recouvrez du reste de mélange et de l'aneth." },
      { step: 3, text: "Filmez bien, posez une planche avec un poids dessus (boîtes de conserve) et réservez au frigo 24 à 36 heures selon l'épaisseur." },
      { step: 4, text: "Rincez le saumon sous l'eau froide, séchez-le délicatement. Tranchez en très fines lamelles à contre-sens des fibres." },
      { step: 5, text: "Servez sur du pain noir avec une crème citronnée à l'aneth, ou en toast pour l'apéro. Effet garanti." },
    ],
  }),
];

export function findMockBySlug(slug: string): Recipe | null {
  return MOCK_RECIPES.find((r) => r.slug === slug) ?? null;
}

/* ============================================================ */
/* Badges drôles + textes de chargement humoristiques            */
/* ============================================================ */

const FUNNY_BADGES = [
  { label: "Inratable (même pour les nuls)", tone: "tomato" as const },
  { label: "Attention : hautement addictif", tone: "slate" as const },
  { label: "Prêt en un éclair (chrono en main)", tone: "sage" as const },
  { label: "Validé par ma grand-mère", tone: "tomato" as const },
  { label: "Effet wow garanti", tone: "slate" as const },
  { label: "Beurre tier list : S+", tone: "sage" as const },
  { label: "Pour épater la belle-mère", tone: "tomato" as const },
];

/** Renvoie un badge drôle déterministe à partir d'un slug. */
export function funnyBadge(slug: string): { label: string; tone: "tomato" | "slate" | "sage" } {
  let h = 0;
  for (let i = 0; i < slug.length; i++) h = (h * 31 + slug.charCodeAt(i)) >>> 0;
  return FUNNY_BADGES[h % FUNNY_BADGES.length];
}

export const FUNNY_LOADING_TEXTS = [
  "Épluchage des oignons en cours…",
  "Vol de frites dans la cuisine…",
  "Ajout d'une pincée de sel et de beaucoup d'amour…",
  "On attend que le beurre arrête de bouder…",
  "Ludo cherche son tablier (encore)…",
  "Préchauffage du four, et de l'humour…",
  "Mise en place : on s'organise comme des chefs…",
];

export function funnyLoading(): string {
  return FUNNY_LOADING_TEXTS[Math.floor(Math.random() * FUNNY_LOADING_TEXTS.length)];
}
