/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as QuiSuisJeRouteImport } from './routes/qui-suis-je'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ConfidentialiteRouteImport } from './routes/confidentialite'
import { Route as ChefLudoSecretZoneRouteImport } from './routes/chef-ludo-secret-zone'
import { Route as CarnetDeRecettesRouteImport } from './routes/carnet-de-recettes'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RecetteIdRouteImport } from './routes/recette.$id'
import { Route as CarnetDeRecettesSlugRouteImport } from './routes/carnet-de-recettes.$slug'
import { Route as CarnetDeRecettesCategorieSlugRouteImport } from './routes/carnet-de-recettes.categorie.$slug'

const QuiSuisJeRoute = QuiSuisJeRouteImport.update({
  id: '/qui-suis-je',
  path: '/qui-suis-je',
  getParentRoute: () => rootRouteImport,
} as any)
const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfidentialiteRoute = ConfidentialiteRouteImport.update({
  id: '/confidentialite',
  path: '/confidentialite',
  getParentRoute: () => rootRouteImport,
} as any)
const ChefLudoSecretZoneRoute = ChefLudoSecretZoneRouteImport.update({
  id: '/chef-ludo-secret-zone',
  path: '/chef-ludo-secret-zone',
  getParentRoute: () => rootRouteImport,
} as any)
const CarnetDeRecettesRoute = CarnetDeRecettesRouteImport.update({
  id: '/carnet-de-recettes',
  path: '/carnet-de-recettes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecetteIdRoute = RecetteIdRouteImport.update({
  id: '/recette/$id',
  path: '/recette/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CarnetDeRecettesSlugRoute = CarnetDeRecettesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CarnetDeRecettesRoute,
} as any)
const CarnetDeRecettesCategorieSlugRoute =
  CarnetDeRecettesCategorieSlugRouteImport.update({
    id: '/categorie/$slug',
    path: '/categorie/$slug',
    getParentRoute: () => CarnetDeRecettesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/carnet-de-recettes': typeof CarnetDeRecettesRouteWithChildren
  '/chef-ludo-secret-zone': typeof ChefLudoSecretZoneRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/contact': typeof ContactRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/qui-suis-je': typeof QuiSuisJeRoute
  '/carnet-de-recettes/$slug': typeof CarnetDeRecettesSlugRoute
  '/recette/$id': typeof RecetteIdRoute
  '/carnet-de-recettes/categorie/$slug': typeof CarnetDeRecettesCategorieSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/carnet-de-recettes': typeof CarnetDeRecettesRouteWithChildren
  '/chef-ludo-secret-zone': typeof ChefLudoSecretZoneRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/contact': typeof ContactRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/qui-suis-je': typeof QuiSuisJeRoute
  '/carnet-de-recettes/$slug': typeof CarnetDeRecettesSlugRoute
  '/recette/$id': typeof RecetteIdRoute
  '/carnet-de-recettes/categorie/$slug': typeof CarnetDeRecettesCategorieSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/carnet-de-recettes': typeof CarnetDeRecettesRouteWithChildren
  '/chef-ludo-secret-zone': typeof ChefLudoSecretZoneRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/contact': typeof ContactRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/qui-suis-je': typeof QuiSuisJeRoute
  '/carnet-de-recettes/$slug': typeof CarnetDeRecettesSlugRoute
  '/recette/$id': typeof RecetteIdRoute
  '/carnet-de-recettes/categorie/$slug': typeof CarnetDeRecettesCategorieSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/carnet-de-recettes'
    | '/chef-ludo-secret-zone'
    | '/confidentialite'
    | '/contact'
    | '/mentions-legales'
    | '/qui-suis-je'
    | '/carnet-de-recettes/$slug'
    | '/recette/$id'
    | '/carnet-de-recettes/categorie/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/carnet-de-recettes'
    | '/chef-ludo-secret-zone'
    | '/confidentialite'
    | '/contact'
    | '/mentions-legales'
    | '/qui-suis-je'
    | '/carnet-de-recettes/$slug'
    | '/recette/$id'
    | '/carnet-de-recettes/categorie/$slug'
  id:
    | '__root__'
    | '/'
    | '/carnet-de-recettes'
    | '/chef-ludo-secret-zone'
    | '/confidentialite'
    | '/contact'
    | '/mentions-legales'
    | '/qui-suis-je'
    | '/carnet-de-recettes/$slug'
    | '/recette/$id'
    | '/carnet-de-recettes/categorie/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CarnetDeRecettesRoute: typeof CarnetDeRecettesRouteWithChildren
  ChefLudoSecretZoneRoute: typeof ChefLudoSecretZoneRoute
  ConfidentialiteRoute: typeof ConfidentialiteRoute
  ContactRoute: typeof ContactRoute
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  QuiSuisJeRoute: typeof QuiSuisJeRoute
  RecetteIdRoute: typeof RecetteIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/qui-suis-je': {
      id: '/qui-suis-je'
      path: '/qui-suis-je'
      fullPath: '/qui-suis-je'
      preLoaderRoute: typeof QuiSuisJeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confidentialite': {
      id: '/confidentialite'
      path: '/confidentialite'
      fullPath: '/confidentialite'
      preLoaderRoute: typeof ConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chef-ludo-secret-zone': {
      id: '/chef-ludo-secret-zone'
      path: '/chef-ludo-secret-zone'
      fullPath: '/chef-ludo-secret-zone'
      preLoaderRoute: typeof ChefLudoSecretZoneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carnet-de-recettes': {
      id: '/carnet-de-recettes'
      path: '/carnet-de-recettes'
      fullPath: '/carnet-de-recettes'
      preLoaderRoute: typeof CarnetDeRecettesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recette/$id': {
      id: '/recette/$id'
      path: '/recette/$id'
      fullPath: '/recette/$id'
      preLoaderRoute: typeof RecetteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carnet-de-recettes/$slug': {
      id: '/carnet-de-recettes/$slug'
      path: '/$slug'
      fullPath: '/carnet-de-recettes/$slug'
      preLoaderRoute: typeof CarnetDeRecettesSlugRouteImport
      parentRoute: typeof CarnetDeRecettesRoute
    }
    '/carnet-de-recettes/categorie/$slug': {
      id: '/carnet-de-recettes/categorie/$slug'
      path: '/categorie/$slug'
      fullPath: '/carnet-de-recettes/categorie/$slug'
      preLoaderRoute: typeof CarnetDeRecettesCategorieSlugRouteImport
      parentRoute: typeof CarnetDeRecettesRoute
    }
  }
}

interface CarnetDeRecettesRouteChildren {
  CarnetDeRecettesSlugRoute: typeof CarnetDeRecettesSlugRoute
  CarnetDeRecettesCategorieSlugRoute: typeof CarnetDeRecettesCategorieSlugRoute
}

const CarnetDeRecettesRouteChildren: CarnetDeRecettesRouteChildren = {
  CarnetDeRecettesSlugRoute: CarnetDeRecettesSlugRoute,
  CarnetDeRecettesCategorieSlugRoute: CarnetDeRecettesCategorieSlugRoute,
}

const CarnetDeRecettesRouteWithChildren =
  CarnetDeRecettesRoute._addFileChildren(CarnetDeRecettesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CarnetDeRecettesRoute: CarnetDeRecettesRouteWithChildren,
  ChefLudoSecretZoneRoute: ChefLudoSecretZoneRoute,
  ConfidentialiteRoute: ConfidentialiteRoute,
  ContactRoute: ContactRoute,
  MentionsLegalesRoute: MentionsLegalesRoute,
  QuiSuisJeRoute: QuiSuisJeRoute,
  RecetteIdRoute: RecetteIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
