-- Catégories étendues pour le dashboard (idempotent)
insert into public.categories (name, slug, emoji, description, display_order) values
  ('Soupes & veloutés', 'soupes-veloutes', '🍵', 'Réconfortants et parfumés', 6),
  ('Salades', 'salades', '🥬', 'Fraîches, croquantes et colorées', 7),
  ('Pâtes & riz', 'pates-riz', '🍝', 'Italien, asiatique et comfort food', 8),
  ('Viandes', 'viandes', '🥩', 'Bœuf, porc, volaille et gibier', 9),
  ('Poissons & fruits de mer', 'poissons-fruits-de-mer', '🐟', 'Océan et rivière à la table', 10),
  ('Végétarien', 'vegetarien', '🥕', 'Sans viande, plein de goût', 11),
  ('Vegan', 'vegan', '🌱', '100 % végétal', 12),
  ('Sans gluten', 'sans-gluten', '🌾', 'Recettes adaptées', 13),
  ('Brunch', 'brunch', '🥞', 'Le meilleur du matin et du midi', 14),
  ('Petit-déjeuner', 'petit-dejeuner', '☕', 'Bien commencer la journée', 15),
  ('Goûter & snacks', 'gouter-snacks', '🍪', 'Douceurs et petites faims', 16),
  ('Boissons', 'boissons', '🍹', 'Cocktails, smoothies et maisons', 17),
  ('Sauces & condiments', 'sauces-condiments', '🫙', 'Pour sublimer chaque plat', 18),
  ('Conserves & bocaux', 'conserves-bocaux', '🫒', 'Anticiper et faire durer', 19),
  ('Cuisine du monde', 'cuisine-du-monde', '🌍', 'Voyager depuis la cuisine', 20),
  ('Cuisine rapide', 'cuisine-rapide', '⚡', 'Bon et vite, sans stress', 21),
  ('Batch cooking', 'batch-cooking', '📦', 'Préparer à l''avance', 22),
  ('Fête & occasions', 'fete-occasions', '🎉', 'Anniversaires, fêtes, réceptions', 23),
  ('Cuisine d''hiver', 'cuisine-hiver', '❄️', 'Plats réconfortants de saison', 24),
  ('Cuisine d''été', 'cuisine-ete', '☀️', 'Léger, frais et ensoleillé', 25),
  ('Tartes salées & quiches', 'tartes-quiches', '🥧', 'Classiques de la table', 26),
  ('Gratins', 'gratins', '🧀', 'Dorés, fondants, irrésistibles', 27),
  ('Barbecue & plancha', 'barbecue-plancha', '🔥', 'Cuisson conviviale dehors', 28),
  ('Fromages', 'fromages', '🧀', 'Plateaux et recettes fromagères', 29),
  ('Accompagnements', 'accompagnements', '🥔', 'Légumes, féculents et sides', 30),
  ('Recettes kids', 'recettes-kids', '👶', 'Simples et ludiques', 31),
  ('Anti-gaspi', 'anti-gaspi', '♻️', 'Cuisiner malin avec les restes', 32),
  ('Pâtisserie fine', 'patisserie-fine', '🎂', 'Technique et élégance', 33),
  ('Chocolat', 'chocolat', '🍫', 'Gourmandise intense', 34),
  ('Fruits & compotes', 'fruits-compotes', '🍎', 'Douceur naturelle', 35),
  ('Tartines & sandwichs', 'tartines-sandwichs', '🥪', 'Rapides et savoureux', 36),
  ('Pizza & calzone', 'pizza-calzone', '🍕', 'Pâte, garniture, four', 37),
  ('Bowls & salades composées', 'bowls', '🥣', 'Équilibrés et colorés', 38),
  ('One-pot', 'one-pot', '🍲', 'Tout dans une casserole', 39),
  ('Air fryer', 'air-fryer', '🌀', 'Croustillant, moins gras', 40)
on conflict (slug) do nothing;
